---
name: lint

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  json:
    name: validate JSON
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: install check-jsonschema
        run: pipx install check-jsonschema
      - name: validate JSON files
        run: ./scripts/validate-json.sh

  dockerfile:
    name: hadolint
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: hadolint
        uses: hadolint/hadolint-action@2332a7b74a6de0dda2e2221d575162eba76ba5e5 # v3.3.0
        with:
          dockerfile: Dockerfile
          config: .hadolint.yaml
